name: Query Runner Streams Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dist: [ 'temurin', 'corretto' ]
        java: [ '11' ]
    steps:
      - name: Remove unused build gunk from runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.dist }}
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: ./gradlew clean test check build --refresh-dependencies --no-daemon --stacktrace
